
CREATE DATABASE T1NET;
USE T1NET; 

CREATE TABLE ALUNO(
    ID INT PRIMARY KEY,
    NOME NVARCHAR(150) NOT NULL,
    DATA_CADASTRO DATETIME DEFAULT GETDATE(),
    OBS VARCHAR(500)
)

-- DROP TABLE ALUNO -- NAO FOI COLOCADO O PRIMARY KEY, ENTAO DELETAMOS, INSERIMOS O PRIMARY KEY E CRIAMOS NOVAMENTE A TABELA.
-- DROP TABLE ALUNO -- USAR O DROP SOMENTE QUANDO NAO TIVER DADOS NA TABELA, POIS COMANDO DROP EXLCUI TUDO

-- ALTER TABLE ALUNO 
-- ADD CPF VARCHAR(11)

-- ALTER TABLE ALUNO
-- DROP COLUMN OBS

CREATE TABLE TELEFONE(
    ID INT PRIMARY KEY,
    TELEFONE VARCHAR(11),
    ID_ALUNO INT REFERENCES ALUNO(ID),
)

CREATE TABLE EMAIL(
    EMAIL VARCHAR(200),
    ID_ALUNO INT REFERENCES ALUNO(ID),
    PRIMARY KEY (EMAIL, ID_ALUNO),
)